### ISSUE TITLE
Setup Help: Airtable

### ISSUE THREAD

**Issue by Integro-Dev** [rl2999/qotd-bot#2]
Hey! This looks like an amazing bot! Thank you for making it open source. I'm having a bit of trouble setting it up and am wondering if you may be able to give some instructions or point me in the right direction. I'm not quite sure how to link Airtable properly or set up the question form, could you be more specific in the setup area of the read me?

Any additional setup information or docs you could provide would be greatly appreciated. Thanks for putting your time into the bot!

**Comment by rl2999** [comment]
Hi there and thank you!
> I'm not quite sure how to link Airtable properly or set up the question form, could you be more specific in the setup area of the read me?
- Copy [my Airtable base template](https://airtable.com/shrMLWzOliJ1avIQo) and add records to the Questions table. There is also an Airtable form that you can publish to receive new questions.

- Rename `envsample.txt` to `.env`, get an Airtable API key and plug it into your `.env` file (different from config.js) along with the Discord key and other fields

If running on Heroku, there is a provided Procfile that specifies "web" as the sole worker; it will run `npm start` for you once the dyno runs.

If running on a VPS:
On your VPS, `cd` to the repo and run `npm start` and the bot should be up and running!
